---
- name: Reload the system (EOS)
  connection: network_cli
  cli_command:
    command: |
      reload now

- name: reset the connection (EOS)
  meta: reset_connection

- name: wait for network device to come back up (EOS)
  pause: 
    minutes: 4
