---
- name: Configure ISL ports (EOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item }}
         no switchport
         no shut
         ip address unnumbered Loopback 0
         mtu 9216
  with_items: "{{ isl_ports[ansible_network_os] }}"
  tags: ospf-isl-cfg

- name: Configure OSPF Parameters (EOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item }}
         ip ospf network point-to-point
         ip ospf area 0.0.0.0
  with_items: "{{ isl_ports[ansible_network_os] }}"
  tags: ospf-isl-cfg

