---
- name: Configure Features in NXOS
  connection: network_cli
  cli_config:
    config: |
      feature privilege
      feature interface-vlan
      feature fabric forwarding
      feature ospf
      feature bgp
      feature pim
      nv overlay evpn
      feature nv overlay
      feature vn-segment-vlan-based

- name: Enable Leaf-only features (NXOS)
  connection: network_cli
  cli_config:
    config: |
      feature vpc
      feature lacp
  when: mlag_info is defined

- name: Set systemwide Jumbo MTU size (NXOS)
  connection: network_cli
  cli_config:
    config: |
      system jumbomtu 9200

