---
- name: Download running config
  connection: network_cli
  cli_command:
     command: show run
  register: backup

- name: Save to local file
  connection: network_cli
  copy:
     content: "{{backup.stdout}}"
     dest: "snapshot/configs/{{inventory_hostname}}.cfg"
