---
- name: Configure server-facing ports (NXOS)
  connection: network_cli
  cli_config:
    config: |
      int {{ item.iface }}
        switchport
        switchport access vlan {{ item.vlanid }}
        mtu 9216
  with_items: "{{ l2_ports[ansible_network_os] }}"

- name: configure SVI (NXOS)
  connection: network_cli
  cli_config: 
    config: |
     interface {{ l2_networks[item.vlanid].vlanif }}
       no shutdown
       mtu 9000
       ip address {{ l2_networks[item.vlanid].ip_address }}

  with_items: "{{ l2_ports[ansible_network_os] }}"

