loopback_ip: 10.0.0.13/32
hw_address: 44:39:39:FF:40:96
bgp_asn: "{{ ibgp_asn }}"

mlag_info:
  clag_sysid: "{{ hw_address }}"
  eos_domainid: mlag_leaf34
  vpc_domainid: 34
  peer_switch: leaf04
  peerlink_ip: 169.254.1.0/31

vtep_ip:
  cumulus:
    - "{{ loopback_ip }}"
    - 10.0.0.134/32
  eos:
    - "{{ loopback_ip }}"
    - 10.0.0.134/32
  nxos:
    - 10.0.0.203/32
    - 10.0.0.134/32


l2_ports:
  cumulus:
    - iface: bond01
      vlanid: 20
    - iface: bond02
      vlanid: 30
  nxos:
    - iface: port-channel3
      vlanid: 20
    - iface: port-channel4
      vlanid: 30
  eos:
    - iface: port-channel3
      vlanid: 20
    - iface: port-channel4
      vlanid: 30
  junos:
    - iface: xe-0/0/2
      vlanid: 20
    - iface: xe-0/0/3
      vlanid: 30

    
